### ISSUE TITLE
Example integrating with jsdoc

### ISSUE THREAD

**Issue by hrgdavor** [jugglinmike/jsdoc-external-example#1]
What needs to be done so jsdoc command recognizes this addon ? Just some example how to run it in the readme :)

**Comment by jugglinmike** [comment]
You're right; I should have included some explanation when I first published this module. I just wrote [a quick `readme.md` file](https://github.com/jugglinmike/jsdoc-external-example/blob/master/readme.md) that gives some context and answers your questions. I hope this helps!
